const enlgishLessonsGroup1: Array<object> = [
  {
    groupName: "English 1",
    groupIndex: 0,
    lessonName: "Intro to English 1",
    lessonIndex: 0,
    progress: "20%",
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Je ____ Lance",
        questionAnswer: "mappelle",
      },
      {
        questionNumber: 2,
        questionType: "Translate this word.",
        questionContext: "Bonjour",
        questionAnswer: "hello",
      },
      {
        questionNumber: 3,
        questionType: "Find the correct translation.",
        questionContext: "Hello",
        questionOptions: ["oui", "bonjour", "content", "merci"],
        questionAnswer: "bonjour",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "bonjour, ____ pour venir",
        questionAnswer: "gracias",
      },
      {
        questionNumber: 5,
        questionType: "Translate this phrase.",
        questionContext: "Je m'appelle Lance",
        questionAnswer: "my name is Lance",
      },
      {
        questionNumber: 6,
        questionType: "Find the missing word.",
        questionContext: "Je ____ Lance",
        questionOptions: ["m'appelle", "bonjour", "oui", "merci"],
        questionAnswer: "mappelle",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Bonjour, ____ bien?",
        questionAnswer: "ca va",
      },
      {
        questionNumber: 8,
        questionType: "Translate this word.",
        questionContext: "comment",
        questionAnswer: "how",
      },
      {
        questionNumber: 9,
        questionType: "Find the correct translation.",
        questionContext: "Thank you",
        questionAnswer: ["oui", "bonjour", "merci", "salut"],
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "____, ça va bien?",
        questionAnswer: "bonjour",
      },
    ],
  },
  {
    groupName: "English 1",
    groupIndex: 0,
    lessonName: "Intro to English 2",
    lessonIndex: 1,
    progress: "40%",
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
  {
    groupName: "English 1",
    groupIndex: 0,
    lessonName: "Intro to English 3",
    lessonIndex: 2,
    progress: "60%",
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
  {
    groupName: "English 1",
    groupIndex: 0,
    lessonName: "Intro to English 4",
    lessonIndex: 3,
    progress: "80%",
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
  {
    groupName: "English 1",
    groupIndex: 0,
    lessonName: "Intro to English 5",
    lessonIndex: 4,
    progress: "100%",
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
];
const enlgishLessonsGroup2: Array<object> = [
  {
    groupName: "English 2",
    groupIndex: 1,
    lessonName: "Medium English 1",
    lessonIndex: 0,
    progress: "100%",
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
  {
    groupName: "English 2",
    groupIndex: 1,
    lessonName: "Medium English 2",
    lessonIndex: 1,
    progress: "20%",
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
  {
    groupName: "English 2",
    groupIndex: 1,
    lessonName: "Medium English 3",
    lessonIndex: 2,
    progress: "40%",
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
  {
    groupName: "English 2",
    groupIndex: 1,
    lessonName: "Medium English 4",
    lessonIndex: 3,
    progress: "60%",
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
  {
    groupName: "English 2",
    groupIndex: 1,
    lessonName: "Medium English 5",
    lessonIndex: 4,
    progress: "80%",
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
];
const enlgishLessonsGroup3: Array<object> = [
  {
    groupName: "English 3",
    groupIndex: 2,
    lessonName: "Pro English 1",
    lessonIndex: 0,
    progress: "80%",
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
  {
    groupName: "English 3",
    groupIndex: 2,
    lessonName: "Pro English 2",
    lessonIndex: 1,
    progress: "100%",
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
  {
    groupName: "English 3",
    groupIndex: 2,
    lessonName: "Pro English 3",
    lessonIndex: 2,
    progress: "20%",
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
  {
    groupName: "English 3",
    groupIndex: 2,
    lessonName: "Pro English 4",
    lessonIndex: 3,
    progress: "40%",
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
  {
    groupName: "English 3",
    groupIndex: 2,
    lessonName: "Pro English 5",
    lessonIndex: 4,
    progress: "60%",
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
];

const EnglishLessons: object[][] = [
  enlgishLessonsGroup1,
  enlgishLessonsGroup2,
  enlgishLessonsGroup3,
];

export default EnglishLessons;
