const enlgishFromPortugueseLessonsGroup1: Array<object> = [
  {
    lessonId: "en1.1",
    groupName: "English 1",
    groupIndex: 0,
    lessonName: "Intro to English 1",
    lessonIndex: 0,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionAnswer: "is",
      },
      {
        questionNumber: 2,
        questionType: "Traduza a palavra.",
        questionContext: "Hello",
        questionAnswer: "ola",
      },
      {
        questionNumber: 3,
        questionType: "Escolha a tradução.",
        questionContext: "Olá",
        questionOptions: ["Yes", "Hello", "Happy", "Thank you"],
        questionAnswer: "hello",
      },
      {
        questionNumber: 4,
        questionType: "Complete a frase.",
        questionContext: "Hello, thank you ____ coming",
        questionAnswer: "for",
      },
      {
        questionNumber: 5,
        questionType: "Traduza a frase.",
        questionContext: "Meu nome é Lance",
        questionAnswer: "my name is Lance",
      },
      {
        questionNumber: 6,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionOptions: ["Is", "Hello", "Yes", "Thank you"],
        questionAnswer: "is",
      },
      {
        questionNumber: 7,
        questionType: "Complete a frase.",
        questionContext: "Hello, how ____ you?",
        questionAnswer: "are",
      },
      {
        questionNumber: 8,
        questionType: "Traduza a palavra.",
        questionContext: "How",
        questionAnswer: "como",
      },
      {
        questionNumber: 9,
        questionType: "Escolha a tradução.",
        questionContext: "Thank you",
        questionOptions: ["Olá", "Tudo bem", "Obrigado", "De nada"],
        questionAnswer: "obrigado",
      },
      {
        questionNumber: 10,
        questionType: "Complete a frase.",
        questionContext: "Hello, _____ is your name?",
        questionAnswer: "what",
      },
    ],
  },
  {
    lessonId: "en1.2",
    groupName: "English 1",
    groupIndex: 0,
    lessonName: "Intro to English 2",
    lessonIndex: 1,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionAnswer: "is",
      },
      {
        questionNumber: 2,
        questionType: "Traduza a palavra.",
        questionContext: "Hello",
        questionAnswer: "ola",
      },
      {
        questionNumber: 3,
        questionType: "Escolha a tradução.",
        questionContext: "Olá",
        questionOptions: ["Yes", "Hello", "Happy", "Thank you"],
        questionAnswer: "hello",
      },
      {
        questionNumber: 4,
        questionType: "Complete a frase.",
        questionContext: "Hello, thank you ____ coming",
        questionAnswer: "for",
      },
      {
        questionNumber: 5,
        questionType: "Traduza a frase.",
        questionContext: "Meu nome é Lance",
        questionAnswer: "my name is Lance",
      },
      {
        questionNumber: 6,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionOptions: ["Is", "Hello", "Yes", "Thank you"],
        questionAnswer: "is",
      },
      {
        questionNumber: 7,
        questionType: "Complete a frase.",
        questionContext: "Hello, how ____ you?",
        questionAnswer: "are",
      },
      {
        questionNumber: 8,
        questionType: "Traduza a palavra.",
        questionContext: "How",
        questionAnswer: "como",
      },
      {
        questionNumber: 9,
        questionType: "Escolha a tradução.",
        questionContext: "Thank you",
        questionOptions: ["Olá", "Tudo bem", "Obrigado", "De nada"],
        questionAnswer: "obrigado",
      },
      {
        questionNumber: 10,
        questionType: "Complete a frase.",
        questionContext: "Hello, _____ is your name?",
        questionAnswer: "what",
      },
    ],
  },
  {
    lessonId: "en1.3",
    groupName: "English 1",
    groupIndex: 0,
    lessonName: "Intro to English 3",
    lessonIndex: 2,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionAnswer: "is",
      },
      {
        questionNumber: 2,
        questionType: "Traduza a palavra.",
        questionContext: "Hello",
        questionAnswer: "ola",
      },
      {
        questionNumber: 3,
        questionType: "Escolha a tradução.",
        questionContext: "Olá",
        questionOptions: ["Yes", "Hello", "Happy", "Thank you"],
        questionAnswer: "hello",
      },
      {
        questionNumber: 4,
        questionType: "Complete a frase.",
        questionContext: "Hello, thank you ____ coming",
        questionAnswer: "for",
      },
      {
        questionNumber: 5,
        questionType: "Traduza a frase.",
        questionContext: "Meu nome é Lance",
        questionAnswer: "my name is Lance",
      },
      {
        questionNumber: 6,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionOptions: ["Is", "Hello", "Yes", "Thank you"],
        questionAnswer: "is",
      },
      {
        questionNumber: 7,
        questionType: "Complete a frase.",
        questionContext: "Hello, how ____ you?",
        questionAnswer: "are",
      },
      {
        questionNumber: 8,
        questionType: "Traduza a palavra.",
        questionContext: "How",
        questionAnswer: "como",
      },
      {
        questionNumber: 9,
        questionType: "Escolha a tradução.",
        questionContext: "Thank you",
        questionOptions: ["Olá", "Tudo bem", "Obrigado", "De nada"],
        questionAnswer: "obrigado",
      },
      {
        questionNumber: 10,
        questionType: "Complete a frase.",
        questionContext: "Hello, _____ is your name?",
        questionAnswer: "what",
      },
    ],
  },
  {
    lessonId: "en1.4",
    groupName: "English 1",
    groupIndex: 0,
    lessonName: "Intro to English 4",
    lessonIndex: 3,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionAnswer: "is",
      },
      {
        questionNumber: 2,
        questionType: "Traduza a palavra.",
        questionContext: "Hello",
        questionAnswer: "ola",
      },
      {
        questionNumber: 3,
        questionType: "Escolha a tradução.",
        questionContext: "Olá",
        questionOptions: ["Yes", "Hello", "Happy", "Thank you"],
        questionAnswer: "hello",
      },
      {
        questionNumber: 4,
        questionType: "Complete a frase.",
        questionContext: "Hello, thank you ____ coming",
        questionAnswer: "for",
      },
      {
        questionNumber: 5,
        questionType: "Traduza a frase.",
        questionContext: "Meu nome é Lance",
        questionAnswer: "my name is Lance",
      },
      {
        questionNumber: 6,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionOptions: ["Is", "Hello", "Yes", "Thank you"],
        questionAnswer: "is",
      },
      {
        questionNumber: 7,
        questionType: "Complete a frase.",
        questionContext: "Hello, how ____ you?",
        questionAnswer: "are",
      },
      {
        questionNumber: 8,
        questionType: "Traduza a palavra.",
        questionContext: "How",
        questionAnswer: "como",
      },
      {
        questionNumber: 9,
        questionType: "Escolha a tradução.",
        questionContext: "Thank you",
        questionOptions: ["Olá", "Tudo bem", "Obrigado", "De nada"],
        questionAnswer: "obrigado",
      },
      {
        questionNumber: 10,
        questionType: "Complete a frase.",
        questionContext: "Hello, _____ is your name?",
        questionAnswer: "what",
      },
    ],
  },
  {
    lessonId: "en1.5",
    groupName: "English 1",
    groupIndex: 0,
    lessonName: "Intro to English 5",
    lessonIndex: 4,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionAnswer: "is",
      },
      {
        questionNumber: 2,
        questionType: "Traduza a palavra.",
        questionContext: "Hello",
        questionAnswer: "ola",
      },
      {
        questionNumber: 3,
        questionType: "Escolha a tradução.",
        questionContext: "Olá",
        questionOptions: ["Yes", "Hello", "Happy", "Thank you"],
        questionAnswer: "hello",
      },
      {
        questionNumber: 4,
        questionType: "Complete a frase.",
        questionContext: "Hello, thank you ____ coming",
        questionAnswer: "for",
      },
      {
        questionNumber: 5,
        questionType: "Traduza a frase.",
        questionContext: "Meu nome é Lance",
        questionAnswer: "my name is Lance",
      },
      {
        questionNumber: 6,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionOptions: ["Is", "Hello", "Yes", "Thank you"],
        questionAnswer: "is",
      },
      {
        questionNumber: 7,
        questionType: "Complete a frase.",
        questionContext: "Hello, how ____ you?",
        questionAnswer: "are",
      },
      {
        questionNumber: 8,
        questionType: "Traduza a palavra.",
        questionContext: "How",
        questionAnswer: "como",
      },
      {
        questionNumber: 9,
        questionType: "Escolha a tradução.",
        questionContext: "Thank you",
        questionOptions: ["Olá", "Tudo bem", "Obrigado", "De nada"],
        questionAnswer: "obrigado",
      },
      {
        questionNumber: 10,
        questionType: "Complete a frase.",
        questionContext: "Hello, _____ is your name?",
        questionAnswer: "what",
      },
    ],
  },
];
const enlgishFromPortugueseLessonsGroup2: Array<object> = [
  {
    lessonId: "en2.1",
    groupName: "English 2",
    groupIndex: 1,
    lessonName: "Medium English 1",
    lessonIndex: 0,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionAnswer: "is",
      },
      {
        questionNumber: 2,
        questionType: "Traduza a palavra.",
        questionContext: "Hello",
        questionAnswer: "ola",
      },
      {
        questionNumber: 3,
        questionType: "Escolha a tradução.",
        questionContext: "Olá",
        questionOptions: ["Yes", "Hello", "Happy", "Thank you"],
        questionAnswer: "hello",
      },
      {
        questionNumber: 4,
        questionType: "Complete a frase.",
        questionContext: "Hello, thank you ____ coming",
        questionAnswer: "for",
      },
      {
        questionNumber: 5,
        questionType: "Traduza a frase.",
        questionContext: "Meu nome é Lance",
        questionAnswer: "my name is Lance",
      },
      {
        questionNumber: 6,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionOptions: ["Is", "Hello", "Yes", "Thank you"],
        questionAnswer: "is",
      },
      {
        questionNumber: 7,
        questionType: "Complete a frase.",
        questionContext: "Hello, how ____ you?",
        questionAnswer: "are",
      },
      {
        questionNumber: 8,
        questionType: "Traduza a palavra.",
        questionContext: "How",
        questionAnswer: "como",
      },
      {
        questionNumber: 9,
        questionType: "Escolha a tradução.",
        questionContext: "Thank you",
        questionOptions: ["Olá", "Tudo bem", "Obrigado", "De nada"],
        questionAnswer: "obrigado",
      },
      {
        questionNumber: 10,
        questionType: "Complete a frase.",
        questionContext: "Hello, _____ is your name?",
        questionAnswer: "what",
      },
    ],
  },
  {
    lessonId: "en2.2",
    groupName: "English 2",
    groupIndex: 1,
    lessonName: "Medium English 2",
    lessonIndex: 1,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionAnswer: "is",
      },
      {
        questionNumber: 2,
        questionType: "Traduza a palavra.",
        questionContext: "Hello",
        questionAnswer: "ola",
      },
      {
        questionNumber: 3,
        questionType: "Escolha a tradução.",
        questionContext: "Olá",
        questionOptions: ["Yes", "Hello", "Happy", "Thank you"],
        questionAnswer: "hello",
      },
      {
        questionNumber: 4,
        questionType: "Complete a frase.",
        questionContext: "Hello, thank you ____ coming",
        questionAnswer: "for",
      },
      {
        questionNumber: 5,
        questionType: "Traduza a frase.",
        questionContext: "Meu nome é Lance",
        questionAnswer: "my name is Lance",
      },
      {
        questionNumber: 6,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionOptions: ["Is", "Hello", "Yes", "Thank you"],
        questionAnswer: "is",
      },
      {
        questionNumber: 7,
        questionType: "Complete a frase.",
        questionContext: "Hello, how ____ you?",
        questionAnswer: "are",
      },
      {
        questionNumber: 8,
        questionType: "Traduza a palavra.",
        questionContext: "How",
        questionAnswer: "como",
      },
      {
        questionNumber: 9,
        questionType: "Escolha a tradução.",
        questionContext: "Thank you",
        questionOptions: ["Olá", "Tudo bem", "Obrigado", "De nada"],
        questionAnswer: "obrigado",
      },
      {
        questionNumber: 10,
        questionType: "Complete a frase.",
        questionContext: "Hello, _____ is your name?",
        questionAnswer: "what",
      },
    ],
  },
  {
    lessonId: "en2.3",
    groupName: "English 2",
    groupIndex: 1,
    lessonName: "Medium English 3",
    lessonIndex: 2,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionAnswer: "is",
      },
      {
        questionNumber: 2,
        questionType: "Traduza a palavra.",
        questionContext: "Hello",
        questionAnswer: "ola",
      },
      {
        questionNumber: 3,
        questionType: "Escolha a tradução.",
        questionContext: "Olá",
        questionOptions: ["Yes", "Hello", "Happy", "Thank you"],
        questionAnswer: "hello",
      },
      {
        questionNumber: 4,
        questionType: "Complete a frase.",
        questionContext: "Hello, thank you ____ coming",
        questionAnswer: "for",
      },
      {
        questionNumber: 5,
        questionType: "Traduza a frase.",
        questionContext: "Meu nome é Lance",
        questionAnswer: "my name is Lance",
      },
      {
        questionNumber: 6,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionOptions: ["Is", "Hello", "Yes", "Thank you"],
        questionAnswer: "is",
      },
      {
        questionNumber: 7,
        questionType: "Complete a frase.",
        questionContext: "Hello, how ____ you?",
        questionAnswer: "are",
      },
      {
        questionNumber: 8,
        questionType: "Traduza a palavra.",
        questionContext: "How",
        questionAnswer: "como",
      },
      {
        questionNumber: 9,
        questionType: "Escolha a tradução.",
        questionContext: "Thank you",
        questionOptions: ["Olá", "Tudo bem", "Obrigado", "De nada"],
        questionAnswer: "obrigado",
      },
      {
        questionNumber: 10,
        questionType: "Complete a frase.",
        questionContext: "Hello, _____ is your name?",
        questionAnswer: "what",
      },
    ],
  },
  {
    lessonId: "en2.4",
    groupName: "English 2",
    groupIndex: 1,
    lessonName: "Medium English 4",
    lessonIndex: 3,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionAnswer: "is",
      },
      {
        questionNumber: 2,
        questionType: "Traduza a palavra.",
        questionContext: "Hello",
        questionAnswer: "ola",
      },
      {
        questionNumber: 3,
        questionType: "Escolha a tradução.",
        questionContext: "Olá",
        questionOptions: ["Yes", "Hello", "Happy", "Thank you"],
        questionAnswer: "hello",
      },
      {
        questionNumber: 4,
        questionType: "Complete a frase.",
        questionContext: "Hello, thank you ____ coming",
        questionAnswer: "for",
      },
      {
        questionNumber: 5,
        questionType: "Traduza a frase.",
        questionContext: "Meu nome é Lance",
        questionAnswer: "my name is Lance",
      },
      {
        questionNumber: 6,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionOptions: ["Is", "Hello", "Yes", "Thank you"],
        questionAnswer: "is",
      },
      {
        questionNumber: 7,
        questionType: "Complete a frase.",
        questionContext: "Hello, how ____ you?",
        questionAnswer: "are",
      },
      {
        questionNumber: 8,
        questionType: "Traduza a palavra.",
        questionContext: "How",
        questionAnswer: "como",
      },
      {
        questionNumber: 9,
        questionType: "Escolha a tradução.",
        questionContext: "Thank you",
        questionOptions: ["Olá", "Tudo bem", "Obrigado", "De nada"],
        questionAnswer: "obrigado",
      },
      {
        questionNumber: 10,
        questionType: "Complete a frase.",
        questionContext: "Hello, _____ is your name?",
        questionAnswer: "what",
      },
    ],
  },
  {
    lessonId: "en2.5",
    groupName: "English 2",
    groupIndex: 1,
    lessonName: "Medium English 5",
    lessonIndex: 4,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionAnswer: "is",
      },
      {
        questionNumber: 2,
        questionType: "Traduza a palavra.",
        questionContext: "Hello",
        questionAnswer: "ola",
      },
      {
        questionNumber: 3,
        questionType: "Escolha a tradução.",
        questionContext: "Olá",
        questionOptions: ["Yes", "Hello", "Happy", "Thank you"],
        questionAnswer: "hello",
      },
      {
        questionNumber: 4,
        questionType: "Complete a frase.",
        questionContext: "Hello, thank you ____ coming",
        questionAnswer: "for",
      },
      {
        questionNumber: 5,
        questionType: "Traduza a frase.",
        questionContext: "Meu nome é Lance",
        questionAnswer: "my name is Lance",
      },
      {
        questionNumber: 6,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionOptions: ["Is", "Hello", "Yes", "Thank you"],
        questionAnswer: "is",
      },
      {
        questionNumber: 7,
        questionType: "Complete a frase.",
        questionContext: "Hello, how ____ you?",
        questionAnswer: "are",
      },
      {
        questionNumber: 8,
        questionType: "Traduza a palavra.",
        questionContext: "How",
        questionAnswer: "como",
      },
      {
        questionNumber: 9,
        questionType: "Escolha a tradução.",
        questionContext: "Thank you",
        questionOptions: ["Olá", "Tudo bem", "Obrigado", "De nada"],
        questionAnswer: "obrigado",
      },
      {
        questionNumber: 10,
        questionType: "Complete a frase.",
        questionContext: "Hello, _____ is your name?",
        questionAnswer: "what",
      },
    ],
  },
];
const enlgishFromPortugueseLessonsGroup3: Array<object> = [
  {
    lessonId: "en3.1",
    groupName: "English 3",
    groupIndex: 2,
    lessonName: "Pro English 1",
    lessonIndex: 0,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionAnswer: "is",
      },
      {
        questionNumber: 2,
        questionType: "Traduza a palavra.",
        questionContext: "Hello",
        questionAnswer: "ola",
      },
      {
        questionNumber: 3,
        questionType: "Escolha a tradução.",
        questionContext: "Olá",
        questionOptions: ["Yes", "Hello", "Happy", "Thank you"],
        questionAnswer: "hello",
      },
      {
        questionNumber: 4,
        questionType: "Complete a frase.",
        questionContext: "Hello, thank you ____ coming",
        questionAnswer: "for",
      },
      {
        questionNumber: 5,
        questionType: "Traduza a frase.",
        questionContext: "Meu nome é Lance",
        questionAnswer: "my name is Lance",
      },
      {
        questionNumber: 6,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionOptions: ["Is", "Hello", "Yes", "Thank you"],
        questionAnswer: "is",
      },
      {
        questionNumber: 7,
        questionType: "Complete a frase.",
        questionContext: "Hello, how ____ you?",
        questionAnswer: "are",
      },
      {
        questionNumber: 8,
        questionType: "Traduza a palavra.",
        questionContext: "How",
        questionAnswer: "como",
      },
      {
        questionNumber: 9,
        questionType: "Escolha a tradução.",
        questionContext: "Thank you",
        questionOptions: ["Olá", "Tudo bem", "Obrigado", "De nada"],
        questionAnswer: "obrigado",
      },
      {
        questionNumber: 10,
        questionType: "Complete a frase.",
        questionContext: "Hello, _____ is your name?",
        questionAnswer: "what",
      },
    ],
  },
  {
    lessonId: "en3.2",
    groupName: "English 3",
    groupIndex: 2,
    lessonName: "Pro English 2",
    lessonIndex: 1,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionAnswer: "is",
      },
      {
        questionNumber: 2,
        questionType: "Traduza a palavra.",
        questionContext: "Hello",
        questionAnswer: "ola",
      },
      {
        questionNumber: 3,
        questionType: "Escolha a tradução.",
        questionContext: "Olá",
        questionOptions: ["Yes", "Hello", "Happy", "Thank you"],
        questionAnswer: "hello",
      },
      {
        questionNumber: 4,
        questionType: "Complete a frase.",
        questionContext: "Hello, thank you ____ coming",
        questionAnswer: "for",
      },
      {
        questionNumber: 5,
        questionType: "Traduza a frase.",
        questionContext: "Meu nome é Lance",
        questionAnswer: "my name is Lance",
      },
      {
        questionNumber: 6,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionOptions: ["Is", "Hello", "Yes", "Thank you"],
        questionAnswer: "is",
      },
      {
        questionNumber: 7,
        questionType: "Complete a frase.",
        questionContext: "Hello, how ____ you?",
        questionAnswer: "are",
      },
      {
        questionNumber: 8,
        questionType: "Traduza a palavra.",
        questionContext: "How",
        questionAnswer: "como",
      },
      {
        questionNumber: 9,
        questionType: "Escolha a tradução.",
        questionContext: "Thank you",
        questionOptions: ["Olá", "Tudo bem", "Obrigado", "De nada"],
        questionAnswer: "obrigado",
      },
      {
        questionNumber: 10,
        questionType: "Complete a frase.",
        questionContext: "Hello, _____ is your name?",
        questionAnswer: "what",
      },
    ],
  },
  {
    lessonId: "en3.3",
    groupName: "English 3",
    groupIndex: 2,
    lessonName: "Pro English 3",
    lessonIndex: 2,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionAnswer: "is",
      },
      {
        questionNumber: 2,
        questionType: "Traduza a palavra.",
        questionContext: "Hello",
        questionAnswer: "ola",
      },
      {
        questionNumber: 3,
        questionType: "Escolha a tradução.",
        questionContext: "Olá",
        questionOptions: ["Yes", "Hello", "Happy", "Thank you"],
        questionAnswer: "hello",
      },
      {
        questionNumber: 4,
        questionType: "Complete a frase.",
        questionContext: "Hello, thank you ____ coming",
        questionAnswer: "for",
      },
      {
        questionNumber: 5,
        questionType: "Traduza a frase.",
        questionContext: "Meu nome é Lance",
        questionAnswer: "my name is Lance",
      },
      {
        questionNumber: 6,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionOptions: ["Is", "Hello", "Yes", "Thank you"],
        questionAnswer: "is",
      },
      {
        questionNumber: 7,
        questionType: "Complete a frase.",
        questionContext: "Hello, how ____ you?",
        questionAnswer: "are",
      },
      {
        questionNumber: 8,
        questionType: "Traduza a palavra.",
        questionContext: "How",
        questionAnswer: "como",
      },
      {
        questionNumber: 9,
        questionType: "Escolha a tradução.",
        questionContext: "Thank you",
        questionOptions: ["Olá", "Tudo bem", "Obrigado", "De nada"],
        questionAnswer: "obrigado",
      },
      {
        questionNumber: 10,
        questionType: "Complete a frase.",
        questionContext: "Hello, _____ is your name?",
        questionAnswer: "what",
      },
    ],
  },
  {
    lessonId: "en3.4",
    groupName: "English 3",
    groupIndex: 2,
    lessonName: "Pro English 4",
    lessonIndex: 3,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionAnswer: "is",
      },
      {
        questionNumber: 2,
        questionType: "Traduza a palavra.",
        questionContext: "Hello",
        questionAnswer: "ola",
      },
      {
        questionNumber: 3,
        questionType: "Escolha a tradução.",
        questionContext: "Olá",
        questionOptions: ["Yes", "Hello", "Happy", "Thank you"],
        questionAnswer: "hello",
      },
      {
        questionNumber: 4,
        questionType: "Complete a frase.",
        questionContext: "Hello, thank you ____ coming",
        questionAnswer: "for",
      },
      {
        questionNumber: 5,
        questionType: "Traduza a frase.",
        questionContext: "Meu nome é Lance",
        questionAnswer: "my name is Lance",
      },
      {
        questionNumber: 6,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionOptions: ["Is", "Hello", "Yes", "Thank you"],
        questionAnswer: "is",
      },
      {
        questionNumber: 7,
        questionType: "Complete a frase.",
        questionContext: "Hello, how ____ you?",
        questionAnswer: "are",
      },
      {
        questionNumber: 8,
        questionType: "Traduza a palavra.",
        questionContext: "How",
        questionAnswer: "como",
      },
      {
        questionNumber: 9,
        questionType: "Escolha a tradução.",
        questionContext: "Thank you",
        questionOptions: ["Olá", "Tudo bem", "Obrigado", "De nada"],
        questionAnswer: "obrigado",
      },
      {
        questionNumber: 10,
        questionType: "Complete a frase.",
        questionContext: "Hello, _____ is your name?",
        questionAnswer: "what",
      },
    ],
  },
  {
    lessonId: "en3.5",
    groupName: "English 3",
    groupIndex: 2,
    lessonName: "Pro English 5",
    lessonIndex: 4,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionAnswer: "is",
      },
      {
        questionNumber: 2,
        questionType: "Traduza a palavra.",
        questionContext: "Hello",
        questionAnswer: "ola",
      },
      {
        questionNumber: 3,
        questionType: "Escolha a tradução.",
        questionContext: "Olá",
        questionOptions: ["Yes", "Hello", "Happy", "Thank you"],
        questionAnswer: "hello",
      },
      {
        questionNumber: 4,
        questionType: "Complete a frase.",
        questionContext: "Hello, thank you ____ coming",
        questionAnswer: "for",
      },
      {
        questionNumber: 5,
        questionType: "Traduza a frase.",
        questionContext: "Meu nome é Lance",
        questionAnswer: "my name is Lance",
      },
      {
        questionNumber: 6,
        questionType: "Complete a frase.",
        questionContext: "My name ____ Lance",
        questionOptions: ["Is", "Hello", "Yes", "Thank you"],
        questionAnswer: "is",
      },
      {
        questionNumber: 7,
        questionType: "Complete a frase.",
        questionContext: "Hello, how ____ you?",
        questionAnswer: "are",
      },
      {
        questionNumber: 8,
        questionType: "Traduza a palavra.",
        questionContext: "How",
        questionAnswer: "como",
      },
      {
        questionNumber: 9,
        questionType: "Escolha a tradução.",
        questionContext: "Thank you",
        questionOptions: ["Olá", "Tudo bem", "Obrigado", "De nada"],
        questionAnswer: "obrigado",
      },
      {
        questionNumber: 10,
        questionType: "Complete a frase.",
        questionContext: "Hello, _____ is your name?",
        questionAnswer: "what",
      },
    ],
  },
];

const EnglishFromPortugueseLessons: object[][] = [
  enlgishFromPortugueseLessonsGroup1,
  enlgishFromPortugueseLessonsGroup2,
  enlgishFromPortugueseLessonsGroup3,
];

export default EnglishFromPortugueseLessons;
