const spanishLessonsGroup1: Array<object> = [
  {
    lessonId: "es1.1",
    groupName: "Spanish 1",
    groupIndex: 0,
    lessonName: "Intro to Spanish 1",
    lessonIndex: 0,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Translate this word.",
        questionContext: "Hola",
        questionAnswer: "hello",
      },
      {
        questionNumber: 3,
        questionType: "Find the correct translation.",
        questionContext: "Hello",
        questionOptions: ["sí", "hola", "feliz", "gracias"],
        questionAnswer: "hola",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Hola, ____ por venir",
        questionAnswer: "gracias",
      },
      {
        questionNumber: 5,
        questionType: "Translate this phrase.",
        questionContext: "Mi nombre es Lance",
        questionAnswer: "my name is Lance",
      },
      {
        questionNumber: 6,
        questionType: "Find the missing word.",
        questionContext: "Mi nombre ____ Lance",
        questionOptions: ["sí", "hola", "es", "gracias"],
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Hola, ¿____ estás?",
        questionAnswer: "como",
      },
      {
        questionNumber: 8,
        questionType: "Translate this word.",
        questionContext: "como",
        questionAnswer: "how",
      },
      {
        questionNumber: 9,
        questionType: "Find the correct translation.",
        questionContext: "Thank you",
        questionAnswer: ["sí", "hola", "es", "gracias"],
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "____, ¿como estás?",
        questionAnswer: "hola",
      },
    ],
  },
  {
    lessonId: "es1.2",
    groupName: "Spanish 1",
    groupIndex: 0,
    lessonName: "Intro to Spanish 2",
    lessonIndex: 1,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
  {
    lessonId: "es1.3",
    groupName: "Spanish 1",
    groupIndex: 0,
    lessonName: "Intro to Spanish 3",
    lessonIndex: 2,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
  {
    lessonId: "es1.4",
    groupName: "Spanish 1",
    groupIndex: 0,
    lessonName: "Intro to Spanish 4",
    lessonIndex: 3,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
  {
    lessonId: "es1.5",
    groupName: "Spanish 1",
    groupIndex: 0,
    lessonName: "Intro to Spanish 5",
    lessonIndex: 4,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
];
const spanishLessonsGroup2: Array<object> = [
  {
    lessonId: "es2.1",
    groupName: "Spanish 2",
    groupIndex: 1,
    lessonName: "Medium Spanish 1",
    lessonIndex: 0,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
  {
    lessonId: "es2.2",
    groupName: "Spanish 2",
    groupIndex: 1,
    lessonName: "Medium Spanish 2",
    lessonIndex: 1,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
  {
    lessonId: "es2.3",
    groupName: "Spanish 2",
    groupIndex: 1,
    lessonName: "Medium Spanish 3",
    lessonIndex: 2,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
  {
    lessonId: "es2.4",
    groupName: "Spanish 2",
    groupIndex: 1,
    lessonName: "Medium Spanish 4",
    lessonIndex: 3,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
  {
    lessonId: "es2.5",
    groupName: "Spanish 2",
    groupIndex: 1,
    lessonName: "Medium Spanish 5",
    lessonIndex: 4,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
];
const spanishLessonsGroup3: Array<object> = [
  {
    lessonId: "es3.1",
    groupName: "Spanish 3",
    groupIndex: 2,
    lessonName: "Pro Spanish 1",
    lessonIndex: 0,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
  {
    lessonId: "es3.2",
    groupName: "Spanish 3",
    groupIndex: 2,
    lessonName: "Pro Spanish 2",
    lessonIndex: 1,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
  {
    lessonId: "es3.3",
    groupName: "Spanish 3",
    groupIndex: 2,
    lessonName: "Pro Spanish 3",
    lessonIndex: 2,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
  {
    lessonId: "es3.4",
    groupName: "Spanish 3",
    groupIndex: 2,
    lessonName: "Pro Spanish 4",
    lessonIndex: 3,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
  {
    lessonId: "es3.5",
    groupName: "Spanish 3",
    groupIndex: 2,
    lessonName: "Pro Spanish 5",
    lessonIndex: 4,
    lessonQuestions: [
      {
        questionNumber: 1,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 2,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 3,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 4,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 5,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 6,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 7,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 8,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 9,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
      {
        questionNumber: 10,
        questionType: "Fill in the blank.",
        questionContext: "Mi nombre ____ Lance",
        questionAnswer: "es",
      },
    ],
  },
];

const SpanishLessons: object[][] = [
  spanishLessonsGroup1,
  spanishLessonsGroup2,
  spanishLessonsGroup3,
];

export default SpanishLessons;
